name: Release
on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            bin: xmirror-server
            artifact: xmirror-server-linux-x86_64-linux
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            bin: xmirror
            artifact: xmirror-macos-aarch64
            target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix develop --accept-flake-config -c cargo build -r --bin ${{ matrix.bin }} --target ${{ matrix.target }}
      - run: cp target/${{ matrix.target }}/release/${{ matrix.bin }} ${{ matrix.artifact }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: bin
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          files: bin/*
          generate_release_notes: true

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix develop --accept-flake-config -c cargo publish -p xmirror-event  --token ${{ secrets.CRATES_IO_TOKEN }}
      - run: nix develop --accept-flake-config -c cargo publish -p xmirror-server --token ${{ secrets.CRATES_IO_TOKEN }}
      - run: nix develop --accept-flake-config -c cargo publish -p xmirror        --token ${{ secrets.CRATES_IO_TOKEN }}
